### ISSUE TITLE
Asking postgres user password

### ISSUE THREAD

**Issue by mustafayildirim** [pavouk-0/postgres-xl-docker#1]
Hi,

When I adding 
`add gtm master gtm_m_1 postgresql-1-gtm-m-1 5432 /var/lib/postgres/data/gtm` 
Docker container asking me postgres user password.
`PGXC add gtm master gtm_m_1 postgresql-1-gtm-m-1 5432 /var/lib/postgres/data/gtm
Initialize GTM master
The authenticity of host 'postgresql-1-gtm-m-1 (10.0.0.4)' can't be established.
ECDSA key fingerprint is da:a7:5c:53:dd:39:a6:57:6a:50:09:06:6c:83:95:f3.
Are you sure you want to continue connecting (yes/no)? yes
postgres@postgresql-1-gtm-m-1's password:`

**Comment by tiredpixel** [comment]
Hi @mustafayildirim. Sorry, I missed this message. Sounds like an SSH key problem. Does the connection work outside of `pgxc_ctl`, e.g. `ssh postgres@postgresql-1-gtm-m-1`?

**Comment by tiredpixel** [comment]
I haven't heard back about this, so I'm going to presume it's sorted. If not, feel free to say. But I recommend you use 0.2.0, if possible, which completely redesigns the approach and doesn't require SSH at all. :)
