### ISSUE TITLE
Kubernetes docker config?

### ISSUE THREAD

**Issue by fire** [pavouk-0/postgres-xl-docker#14]
Are you working on a kubernetes config? Your postgres-xl setup removed ssh, which was a major obstacle in kubernetizing it. So now that that blocker is gone I can see an approach.

Hopefully I can find some time to work on it.

**Comment by tiredpixel** [comment]
Hi @fire! :) I'm not currently, because Docker Swarm has been enough for my current main project, but I'm very open to the idea, ideally supporting someone who wants to work on it, but potentially drafting it myself if there's enough interest (and I find time). :)

**Comment by tiredpixel** [comment]
Closing, because I see nothing complex about using the latest Postgres-XL Docker images in Kubernetes. If anyone tries it and encounters any difficulties, please say. :)
