### ISSUE TITLE
cmd script => unclean shutdown

### ISSUE THREAD

**Issue by tiredpixel** [pavouk-0/postgres-xl-docker#18]
The `cmd` scripts do not forward signals, or pass execution to the `postgres` programs. The prevents the db from shutting down cleanly in response to signals.

**Comment by fandikurnia** [comment]
db_coord_1_1  | LOG:  cluster monitor started
db_data_2_1   | LOG:  MultiXact member wraparound protections are now enabled
db_data_2_1   | LOG:  database system is ready to accept connections
db_data_2_1   | LOG:  cluster monitor started
db_data_2_1   | LOG:  autovacuum launcher started
db_coord_2_1  | LOG:  database system was not properly shut down; automatic recovery in progress
db_coord_2_1  | LOG:  redo starts at 0/1582BF8
db_coord_2_1  | LOG:  invalid record length at 0/158E820
db_coord_2_1  | LOG:  redo done at 0/158D998
db_coord_2_1  | LOG:  last completed transaction was at log time 2017-10-12 02:17:58.28579+00
db_coord_2_1  | LOG:  MultiXact member wraparound protections are now enabled
db_coord_2_1  | LOG:  database system is ready to accept connections
db_coord_2_1  | LOG:  cluster monitor started
db_coord_2_1  | LOG:  autovacuum launcher started
db_gtm_1_1    | 1:3422549760:2017-10-12 02:20:45.739 UTC -FATAL:  Expecting a startup message, but received G
db_gtm_1_1    | LOCATION:  GTM_ThreadMain, main.c:1098
db_gtm_1_1    | 1:3414157056:2017-10-12 02:21:15.811 UTC -FATAL:  Expecting a startup message, but received G
db_gtm_1_1    | LOCATION:  GTM_ThreadMain, main.c:1098

root@docker:/home/fandi/postgres-xl-docker# docker ps 
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS                    PORTS               NAMES
acc6ae07966e        tiredpixel/postgres-xl:XL9_5_STABLE-794-ged34d4e   "docker-entrypoint..."   40 seconds ago      Up 38 seconds (healthy)                       postgresxldocker_db_coord_2_1
1eea8d658fef        tiredpixel/postgres-xl:XL9_5_STABLE-794-ged34d4e   "docker-entrypoint..."   40 seconds ago      Up 39 seconds (healthy)                       postgresxldocker_db_data_1_1
1c18591a7526        tiredpixel/postgres-xl:XL9_5_STABLE-794-ged34d4e   "docker-entrypoint..."   40 seconds ago      Up 38 seconds (healthy)                       postgresxldocker_db_data_2_1
779e663bf92e        tiredpixel/postgres-xl:XL9_5_STABLE-794-ged34d4e   "docker-entrypoint..."   40 seconds ago      Up 38 seconds (healthy)                       postgresxldocker_db_coord_1_1
2cf19d92b43a        tiredpixel/postgres-xl:XL9_5_STABLE-794-ged34d4e   "docker-entrypoint..."   40 seconds ago      Up 39 seconds (healthy)                       postgresxldocker_db_gtm_1_1

**Comment by tiredpixel** [comment]
Fixed.
Will be released shortly in version `XL9_5_STABLE-796-gb21d18d`.
