### ISSUE TITLE
./Configure No such file or directory 

### ISSUE THREAD

**Issue by fandikurnia** [pavouk-0/postgres-xl-docker#19]
HI tiredpixel 
problem to build docker-compose. 
---> e5573d5c35c6
Step 14/23 : RUN ./configure --prefix ${PG_LIB}     &&     make     &&     cd contrib/pgxc_ctl     &&     make
 ---> Running in b472b4fe9ab5
/bin/sh: ./configure: No such file or directory
ERROR: Service 'db_gtm_1' failed to build: The command '/bin/sh -c ./configure --prefix ${PG_LIB}     &&     make     &&     cd contrib/pgxc_ctl     &&     make' returned a non-zero code: 127

**Comment by tiredpixel** [comment]
Hi @fandikurnia.
Hm, strange. Which version of Postgres-XL Docker are you using? (`git describe`) Which version of Docker Compose are you using? And which version of Docker are you using?
Thanks. :)

**Comment by tiredpixel** [comment]
p.s. You only need to build this if you want to develop Postgres-XL Docker locally, for some reason; otherwise, you can go straight to using the pre-built images on Docker Hub:
https://hub.docker.com/r/tiredpixel/postgres-xl/

**Comment by fandikurnia** [comment]
I'm using version 0.2.0 , 0.3.0 and master, but everything is failed. sorry i don't understand need to build ? yes I try to use locallly. 

My Docker-compose version
root@docker:/home/fandi# docker-compose --version
docker-compose version 1.15.0, build e12f3b9

**Comment by fandikurnia** [comment]
root@docker:/home/fandi/postgres-xl-docker# git describe
XL9_5_STABLE-794-ged34d4e


thanks

**Comment by tiredpixel** [comment]
@fandikurnia, thanks. What I mean is that unless you're wanting to build from source, you can just change
```yml
build: .
```
lines to
```yml
image: tiredpixel/postgres-xl:XL9_5_STABLE-794-ged34d4e
```
and you can use the pre-compiled versions directly.

However, to do what you're trying to do, please use version `XL9_5_STABLE-794-ged34d4e` or `master`. I suspect that you haven't initialised your Git submodules correctly. What does
```sh
ls lib/postgres-xl/
```
show? If it's empty, that's the problem. :)

**Comment by fandikurnia** [comment]
ok, I have changed and it's still working. 

pre-compile ? yes still empty I using master branch right now.

**Comment by fandikurnia** [comment]
db_coord_1_1  | LOG:  cluster monitor started
db_data_2_1   | LOG:  MultiXact member wraparound protections are now enabled
db_data_2_1   | LOG:  database system is ready to accept connections
db_data_2_1   | LOG:  cluster monitor started
db_data_2_1   | LOG:  autovacuum launcher started
db_coord_2_1  | LOG:  database system was not properly shut down; automatic recovery in progress
db_coord_2_1  | LOG:  redo starts at 0/1582BF8
db_coord_2_1  | LOG:  invalid record length at 0/158E820
db_coord_2_1  | LOG:  redo done at 0/158D998
db_coord_2_1  | LOG:  last completed transaction was at log time 2017-10-12 02:17:58.28579+00
db_coord_2_1  | LOG:  MultiXact member wraparound protections are now enabled
db_coord_2_1  | LOG:  database system is ready to accept connections
db_coord_2_1  | LOG:  cluster monitor started
db_coord_2_1  | LOG:  autovacuum launcher started
db_gtm_1_1    | 1:3422549760:2017-10-12 02:20:45.739 UTC -FATAL:  Expecting a startup message, but received G
db_gtm_1_1    | LOCATION:  GTM_ThreadMain, main.c:1098
db_gtm_1_1    | 1:3414157056:2017-10-12 02:21:15.811 UTC -FATAL:  Expecting a startup message, but received G
db_gtm_1_1    | LOCATION:  GTM_ThreadMain, main.c:1098
root@docker:/home/fandi/postgres-xl-docker# docker ps 
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS                    PORTS               NAMES
acc6ae07966e        tiredpixel/postgres-xl:XL9_5_STABLE-794-ged34d4e   "docker-entrypoint..."   40 seconds ago      Up 38 seconds (healthy)                       postgresxldocker_db_coord_2_1
1eea8d658fef        tiredpixel/postgres-xl:XL9_5_STABLE-794-ged34d4e   "docker-entrypoint..."   40 seconds ago      Up 39 seconds (healthy)                       postgresxldocker_db_data_1_1
1c18591a7526        tiredpixel/postgres-xl:XL9_5_STABLE-794-ged34d4e   "docker-entrypoint..."   40 seconds ago      Up 38 seconds (healthy)                       postgresxldocker_db_data_2_1
779e663bf92e        tiredpixel/postgres-xl:XL9_5_STABLE-794-ged34d4e   "docker-entrypoint..."   40 seconds ago      Up 38 seconds (healthy)                       postgresxldocker_db_coord_1_1
2cf19d92b43a        tiredpixel/postgres-xl:XL9_5_STABLE-794-ged34d4e   "docker-entrypoint..."   40 seconds ago      Up 39 seconds (healthy)                       postgresxldocker_db_gtm_1_1
root@docker:/home/fandi/postgres-xl-docke

**Comment by tiredpixel** [comment]
If you're using `master` and building from source using `build:` in `docker-compose.yml` rather than `image:`, you'll need to make sure you initialised the Git submodule correctly. `ls lib/postgres-xl/` should *not* be empty. e.g.
```sh
git submodule update --init
```
Alternatively, clone the repository using
```sh
git clone <URL> --recursive
```
