### ISSUE TITLE
pgxc_ctl: remove

### ISSUE THREAD

**Issue by tiredpixel** [pavouk-0/postgres-xl-docker#20]
It's causing confusion. I won't support it anymore; it's not needed. Instead, issue clustering commands directly using the approach in the README or bootstrap scripts.

**Comment by tiredpixel** [comment]
Planning this for the next round of work on Postgres-XL Docker.

**Comment by Miazzy** [comment]
Come on, complete docker's Postgres-XL, will bring many people a quick and efficient deployment task! Thank you for doing such an excellent job!

**Comment by tiredpixel** [comment]
Done in `1858d36`.
