### ISSUE TITLE
failure at step 14/23

### ISSUE THREAD

**Issue by rizvnn** [pavouk-0/postgres-xl-docker#21]
Hi,
I'm getting the following error when running docker-compose up

Step 14/23 : RUN ./configure --prefix ${PG_LIB}     &&     make     &&     cd contrib/pgxc_ctl     &&     make
 ---> Running in 16d70c6440a4
/bin/sh: ./configure: No such file or directory
ERROR: Service 'db_gtm_1' failed to build: The command '/bin/sh -c ./configure --prefix ${PG_LIB}     &&     make     &&     cd contrib/pgxc_ctl     &&     make' returned a non-zero code: 127

is the configure directory missing in the git repository?

Thanks
Riz

**Comment by tiredpixel** [comment]
Hi. :) Sounds like the source directory is empty. Have you initialised the Git Submodules?

**Comment by tiredpixel** [comment]
p.s. There are also pre-built images on Docker Hub you can use, if you don't want to build it yourself.

**Comment by rizvnn** [comment]
thanks will give the pre-built images a go
