### ISSUE TITLE
PG_NET_CLUSTER_A remove

### ISSUE THREAD

**Issue by tiredpixel** [pavouk-0/postgres-xl-docker#22]
`PG_NET_CLUSTER_A`, `PG_NET_CLUSTER_B` is fiddly to use correctly. Replace with a better solution.

**Comment by tiredpixel** [comment]
Planning this for the next round of work on Postgres-XL Docker. Booting test clusters with varying networks makes this very irritating. :)

**Comment by Miazzy** [comment]
really good job !

**Comment by tiredpixel** [comment]
Done in `03fb388`.
