### ISSUE TITLE
 configure file in which directory?

### ISSUE THREAD

**Issue by Thebigwind** [pavouk-0/postgres-xl-docker#23]
When I build docker，a problem has arisen. configure file in which directory?
Step 14 : RUN ./configure --prefix ${PG_LIB}     &&     make     &&     cd contrib/pgxc_ctl     &&     make
 ---> Running in 31ff5f483293
/bin/sh: ./configure: No such file or directory
The command '/bin/sh -c ./configure --prefix ${PG_LIB}     &&     make     &&     cd contrib/pgxc_ctl     &&     make' returned a non-zero code: 127
wish your reply.

**Comment by tiredpixel** [comment]
@Thebigwind, sounds like you haven't checked out the Postgres-XL source, which is contained in this project in a Git submodule. Does the information in https://github.com/tiredpixel/postgres-xl-docker/issues/19 sort your issue?

**Comment by tiredpixel** [comment]
Note that there is no need to compile it yourself unless you're doing something special development-wise; otherwise, you can just use the pre-compiled images I supply to Docker Hub. #19 contains more information.

**Comment by tiredpixel** [comment]
No response in months, so closing.
