### ISSUE TITLE
healthchecks order vs health

### ISSUE THREAD

**Issue by tiredpixel** [pavouk-0/postgres-xl-docker#25]
If one or more data nodes are reported as unhealthy before coord nodes healthchecks have fired, there is no `_healthcheck` database. Subsequent attempts by coord nodes to create the database will lead to a failure for one or more data nodes, since unhealthy traffic is not routed (I *think*). This leads to a broken cluster on init.

**Comment by tiredpixel** [comment]
p.s. Until I get chance to fix this, a workaround meanwhile is to execute `docker-healthcheck-coord` manually in bash on a coord node immediately after init, prior to data nodes healthchecks firing.

Disabling data node healthchecks until post-init would likely also sort the issue.

**Comment by stephenstubbs** [comment]
I'm setting up a wait for file for my use at the moment like you suggested. Would you like me to do a pull request with this?

**Comment by stephenstubbs** [comment]
Nevermind even with a file in a place and an if checking against it the healthcheck still waits for the interval before the container is visible on the network. It seems there isn't a way to get the healthcheck to run earlier without making the interval really small.

**Comment by tiredpixel** [comment]
I've completely reworked the healthchecks. Would you mind taking a look at Docker Hub image
`pavouk0/postgres-xl:XL_10_R1_1-6-g68c378f-4-g7a65119`
please? It implements the file check, allows routing and the cluster to establish in a bootstrapping phase, and then switches to a proper healthcheck once that's active. It's passed my initial tests, both locally and using the built image on a Docker Swarm cluster.

Please see https://github.com/pavouk-0/postgres-xl-docker/pull/32 for more details.

You're right that it will wait for the first healthcheck—however, this should happen in `30 s`, and it should usually stabilise within around `60 s`, and against within about the same post-init (which there is no longer a rush to run, healthcheck-wise). I think this is likely acceptable for the first run of a database cluster.

**Comment by stephenstubbs** [comment]
Brilliant thanks I will test this today.

**Comment by tiredpixel** [comment]
Seems fine to me. This will be included in the next release.
