### ISSUE TITLE
Postgres-XL  10r1.1

### ISSUE THREAD

**Issue by wahello** [pavouk-0/postgres-xl-docker#26]
Postgres-XL [ new version 10r1.1](https://www.postgres-xl.org/documentation/)n was released

**Comment by tiredpixel** [comment]
Thanks. Looking into this now. We're transferring the repo and Docker builds to Pavouk's organisation, rather than my own personal one. This should make it easier for us to update builds quicker, in future.

**Comment by tiredpixel** [comment]
2 new versions have been packaged:
`XL9_5_STABLE-1017-gaed0774`
`XL_10_R1_1-6-g68c378f`
These are currently being built by CI, and should be available in their new home shortly:
https://hub.docker.com/r/pavouk0/postgres-xl
https://github.com/pavouk-0/postgres-xl-docker
