### ISSUE TITLE
jammy healthcheck createdb

### ISSUE THREAD

**Issue by tiredpixel** [pavouk-0/postgres-xl-docker#37]
I appear to have introduced a regression in the latest healthchecks. :( I haven't been able to reproduce it every time, but now rather a lot of times, with both the Docker Hub images and the development source version. In brief, it's thus: sometimes, the healthcheck database never gets created. The `createdb` call hangs indefinitely, and bootstrapping never completes. However, killing the process appears to allow the call to succeed on the next try, and bootstrapping completes.

**Comment by tiredpixel** [comment]
Longer explanation added in 524baac .

**Comment by tiredpixel** [comment]
For clarity:

[#37] healthcheck-coord: hack jammy healthchecks, with random sleep

There appears to be a race-condition with calling `createdb` from 2 Coordinators at once. This is reproducible multiple times, on both the Docker Hub images and building this from source. Since the healthchecks were reworked, sometimes `createdb` freezes, and bootstrapping never completes. I've since found that killing the `createdb` process allows the bootstrapping to complete.

Adding a random sleep also appears to avoid the race-condition, and allow the bootstrapping to complete (!). If this is confirmed, then this is surely a bug in upstream Postgres-XL; I don't see anything in the packaging itself which could lead to this. Let's try to get some confirmations, and report it upstream, if so. At least with the Postgres-XL Docker images, then reproducing things and tearing down and rebuilding clusters is actually pretty straightforward.

Note that this does not appear to affect `createuser`, for some reason.

**Comment by stephenstubbs** [comment]
I will run some tests on this too.

**Comment by LamaAni** [comment]
PR is up.

**Comment by tiredpixel** [comment]
Did anyone perhaps have a chance to test this? :) Has anyone else experienced the bugs I was fixing?

**Comment by LamaAni** [comment]
Hi, sorry no I have not integrated the health checks into the helm chart yet, currently I am using simple health checks as bash scripts. 

If you like you can see which health checks we are doing [here](https://github.com/LamaAni/postgres-xl-helm/tree/master/scripts), In the scripts labeled probe_* and check_*

**Comment by stephenstubbs** [comment]
I'm sorry I didn't reply to this. I have tested this and experienced it too. Also running "create database" in sql on multiple coordinators at the same time can sometimes do it. Workaround was just to run the sql on one node by adding an env variable to one node so bootstrapping only happens on it but yes this does appear to be a bug.

I haven't experienced this with anything except create database.

**Comment by LamaAni** [comment]
@sstubbs 
Can you post the reproduce steps? I would like to test this also.

**Comment by stephenstubbs** [comment]
In the coordinator entrypoint I included this

`sleep 90 && init-setup-users &`

before

` exec "$@"`

and init-setup-users included this

```
#!/bin/sh -eu
#-----------------------------------------------------------------------------
# GET CREDENTIALS FOR USERS
FINAL_CREDENTIALS="{}"
if [ ${PG_SECRET_NAME+"false"} ]
then
        FINAL_CREDENTIALS=$(cat "/run/secrets/$PG_SECRET_NAME")
else
        if [ ${PG_CREDENTIALS+"false"} ]
        then
                FINAL_CREDENTIALS=$PG_CREDENTIALS
        fi
fi
#-----------------------------------------------------------------------------
# CREATE AND UPDATE CREDENTIALS FOR SUPERUSER
SUPERUSER_NAME=$(echo "$FINAL_CREDENTIALS" | jq -r '"\(.superuserName)"')
SUPERUSER_PASSWORD=$(echo "$FINAL_CREDENTIALS" | jq -r '"\(.superuserPassword)"')
psql -c "CREATE ROLE ${SUPERUSER_NAME} WITH SUPERUSER PASSWORD '${SUPERUSER_PASSWORD}' LOGIN;" || true
psql -c "ALTER ROLE ${SUPERUSER_NAME}  WITH SUPERUSER PASSWORD '${SUPERUSER_PASSWORD}' LOGIN;" || true
#-----------------------------------------------------------------------------
# CREATE AND UPDATE CREDENTIALS FOR REPLICATION USER
REPLICATION_USERNAME=$(echo "$FINAL_CREDENTIALS" | jq -r '"\(.replicationUsername)"')
REPLICATION_USER_PASSWORD=$(echo "$FINAL_CREDENTIALS" | jq -r '"\(.replicationUserPassword)"')
psql -c "CREATE ROLE ${REPLICATION_USERNAME} WITH REPLICATION PASSWORD '${REPLICATION_USER_PASSWORD}' LOGIN;" || true
psql -c "ALTER ROLE ${REPLICATION_USERNAME}  WITH REPLICATION PASSWORD '${REPLICATION_USER_PASSWORD}' LOGIN;" || true
#-----------------------------------------------------------------------------
# CREATE AND UPDATE CREDENTIALS FOR CONNECTION POOL USER
CONNECTION_POOL_USERNAME=$(echo "$FINAL_CREDENTIALS" | jq -r '"\(.connectionPoolUserName)"')
CONNECTION_POOL_USER_PASSWORD=$(echo "$FINAL_CREDENTIALS" | jq -r '"\(.connectionPoolUserPassword)"')
psql -c "CREATE ROLE ${CONNECTION_POOL_USERNAME} WITH PASSWORD '${CONNECTION_POOL_USER_PASSWORD}' LOGIN;" || true
psql -c "ALTER ROLE ${CONNECTION_POOL_USERNAME}  WITH PASSWORD '${CONNECTION_POOL_USER_PASSWORD}' LOGIN;" || true
#-----------------------------------------------------------------------------
# SETUP DYNAMIC CONNECTION POOL FUNCTION
LOOKUP_FUNCTION="
CREATE SCHEMA IF NOT EXISTS connection_pool;
GRANT USAGE ON SCHEMA connection_pool TO ${CONNECTION_POOL_USERNAME};
CREATE OR REPLACE FUNCTION connection_pool.lookup (
   INOUT p_user     name,
   OUT   p_password text
) RETURNS record
   LANGUAGE sql SECURITY DEFINER SET search_path = pg_catalog AS
\$FUNC\$ SELECT usename, passwd FROM pg_shadow WHERE usename = p_user \$FUNC\$;
REVOKE EXECUTE ON FUNCTION connection_pool.lookup(name) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION connection_pool.lookup(name) TO ${CONNECTION_POOL_USERNAME};
"
psql -d template1 -c "${LOOKUP_FUNCTION}" || true
psql -d postgres -c "${LOOKUP_FUNCTION}" || true
sleep 5
psql -c "CLEAN CONNECTION TO ALL FOR template1;"
sleep 5
psql -c "CREATE DATABASE ${SUPERUSER_NAME};" || true
#-----------------------------------------------------------------------------
```

**Comment by stephenstubbs** [comment]
The way I got around it was PG_INIT_USERS_NODE variable to each node and running it like this
```
       if [ "${PG_INIT_USERS_NODE}" = "${PG_NODE}" ]
          then
          sleep 90 && init-setup-users &
        fi
```
Not ideal I know but seemed to work with the testing I did

**Comment by tiredpixel** [comment]
Thanks for the testing. It sounds like there is indeed a race-condition issue in upstream Postgres-XL, and that people are trying to avoid it in various ways. That makes me think that my patch is beneficial, and certainly, shouldn't do any harm. I've opened it as a PR, and intend to merge it shortly and cut a new release.
https://github.com/pavouk-0/postgres-xl-docker/pull/45
Thanks, everyone.
