### ISSUE TITLE
Error with long host names

### ISSUE THREAD

**Issue by LamaAni** [pavouk-0/postgres-xl-docker#43]
## What

When calling `create node` command, the HOST property has a maximum number of characters. This causes the hostname to be truncated, which leads to connection issues between the pods.

The long hostname is required by the StatefulSet in kubernetes, since its defined as
[STS name].[POD-Name] which can be very long.

## The error
Connection issues between the pods.

## Proposal
Change permissions of the /etc/hosts file to allow host aliases to be added by the postgres user. In this case, we can add local aliases when connecting to the other containers and bypass the issue.

**Comment by stephenstubbs** [comment]
I also have had this issue. Would it be possible to add this? It would be really helpful.

**Comment by tiredpixel** [comment]
Hm… changing permissions of `/etc/hosts` to be non-root user? That would be very unusual. I imagine it could be a security risk, too… :|

Any reason why you can't add the hosts entries the normal Kubernetes way?
https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/

**Comment by LamaAni** [comment]
The default kubernetes hosts only allows IP. The hosts file should do the same. I am checking other options. 

I'll be out for the weekend so prob. only mid next week.

**Comment by tiredpixel** [comment]
Oh, I see. Yes, you would need to know the IP for that, which could of course change. Sounds like you need to create some sort of network alias, or allow it to also respond under the shortname. What happens if you change the resolver search path to including the part after the first FQDN dot?
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods

e.g. I have a server with FQDN `vm-env-grp-id.grp.env.vm.example.com`. That resolves fine, but it's long, so I want `vm-env-grp-id` to work, too. So I set `/etc/resolv.conf`
```
search grp.env.vm.example.com
```
and now `vm-env-grp-id` works, too. In Kubernetes world, for example:
```yaml
apiVersion: v1
kind: Pod
spec:
  # dnsPolicy: "None" # not sure if this is needed; if so, you'll need to set nameservers, too
  dnsConfig:
    searches:
      - grp.env.vm.example.com
```
or something like that.

**Comment by LamaAni** [comment]
Hi, sorry for the late return I was in a festival this weekend. 

Yes, I believe your approach is definitely valuable, though I wonder how it would work with a stateful set. I also like this approach since it is controlled directly by kubernetes rather then another startup script.  

I will fully attempt this, and let you know.  I am also considering changing the base chart name to have shorter names (postgres-xl -> pgxl), that way more chars are left for the name resolving. I believe these two together should resolve this issue. 

Thank you for your help.

**Comment by LamaAni** [comment]
@sstubbs @tiredpixel 

After long deliberations with myself ;) and some direct testing it seems that the `searches` method dose not work with STS. This is because the STS direct pod name, i.e. `pod-0.my-sts.[namespace].svc....` is actually a sub-domain, and the scan dose not allow that. 

So, instead I followed this [approach](https://askubuntu.com/questions/701903/how-do-i-create-my-own-custom-hosts-file),
1. I set the env `HOSTALIASES=/config/host_aliases`, in the shared env set for all running containers.
2. Using the `config` ConfigMap mount I added the host_aliases file, and made a short alias for each of the nodes. 
3. I change the CREATE NODE command to match the aliases. 

Now, it dose not matter what is the length of the chart and what is the url resolve and subdomain is. 

Thank you both very much for your help. You can see the PR here: https://github.com/LamaAni/postgres-xl-helm/pull/39

**Comment by LamaAni** [comment]
This issue can be closed.

**Comment by tiredpixel** [comment]
Thanks, @LamaAni !
