### ISSUE TITLE
Waiting for new 10_R1 release with netcat

### ISSUE THREAD

**Issue by LamaAni** [pavouk-0/postgres-xl-docker#44]
Hi, is the new 10_R1 release with netcat available on dockerhub?

Also, what is the difference between 10_STABLE and 10_R1? is the branch 10_STABLE available on dockerhub?

**Comment by tiredpixel** [comment]
Hi. Not yet, I'm afraid; I wanted to get #37 sorted before any new release. Since it sounds like there is indeed an issue there, I've opened a PR, and tend to merge and release it over the next day or two.
https://github.com/pavouk-0/postgres-xl-docker/issues/37

**Comment by tiredpixel** [comment]
New releases are now available on Docker Hub.
https://www.pavouk.tech/2019/10/25/postgres-xl-docker-releases-2/
