### ISSUE TITLE
Package rsync is missing

### ISSUE THREAD

**Issue by LamaAni** [pavouk-0/postgres-xl-docker#46]
Hi,

Would it be possible to add the `rsync` package to the image? I require it for WAL archiving.

Scenario (postgres wal archiving)
```shell
#!/usr/bin/env bash
cur_path="$(dirname ${BASH_SOURCE[0]})"
source "$cur_path/common.sh"

# loading env.
SOURCE_WAL_FILE="$1"
TARGET_WAL_ARCHIVE_NAME="$2"

: ${WAL_ARCHIVE_PATH:="$STORAGE_MOUNT_PATH/wal_archive"}

if [ ! -d "$WAL_ARCHIVE_PATH" ]; then
  mkdir -p "$WAL_ARCHIVE_PATH"
  assert $? "Failed to create archive directory" || exit $?

  log:archive "Created archive directory @ $WAL_ARCHIVE_PATH"
fi

archive_to_path="$WAL_ARCHIVE_PATH/$TARGET_WAL_ARCHIVE_NAME"

# invoke backup logging.
# TODO: replace with rsync
cp -f "$SOURCE_WAL_FILE" "$archive_to_path"
assert $? "Error while archiving WAL $SOURCE_WAL_FILE -> $archive_to_path"
log:archive "Archived WAL file $SOURCE_WAL_FILE -> $archive_to_path"
```

**Comment by tiredpixel** [comment]
Hm. I'm not entirely sure I understand the use-case. If you're trying to ship WAL files, is that not possible external to the image, or via a shared volume? And regardless, does Postgres-XL not support Replication Slots, instead?

**Comment by LamaAni** [comment]
As you probably know, in postgres-xl there is a way to store wal files when these are created. The wal_archive.

Since the recommended methodology in kubenetes to store backup data is a pvc. The best way to do this is to mount a backup folder, as a separate pvc and use this pvc to send data to GKE (or other) devices. Notably, this can be done with `cp`. But doing so with rsync is the recommended method. See here: https://www.postgres-xl.org/documentation/continuous-archiving.html

For the restore, it is best to use rsync 
> ...For example, some versions of rsync return a separate exit code for “vanished source files”,...

Also, [here](https://wiki.postgresql.org/wiki/Warm_Standby), you can see a warm standby example, where `archive_command` is,
```shell
rsync -a %p postgres@standbyhost:/path/to/wal_archive/%f
```

As I understand it, the `rsync` removes some of the multiple copies, if larger wal archives are used, especially for the restore.

**Comment by tiredpixel** [comment]
Yes, I'm familiar with PostgreSQL replication methods.

I see, so you're using the rsync as part of the `archive_command`; I didn't realise that, when reading your first message. In that case, I'm open to the idea.

However, please note my question about replication slots; is there some reason you're not using them? (I don't actually know if Postgres-XL supports them or not.)

**Comment by LamaAni** [comment]
Hum... the replication question is still open. I am not sure that I will use the slots, but for sure the `archive_command` is a good idea. In case where there is a failure, I am thinking:
1. Replication = Hot standby - high aviability
2. wal_archive and restore = database backup to bucket (or GKE drive with auto restore). 

Would love ur opinion on this.

**Comment by tiredpixel** [comment]
Sounds like a good plan to me. The WAL segments will allow PITR, of course, if that database requires that sort of safety. But for the replication itself, you have two options: shipping WAL segments (e.g. using Rsync, as you suggest), or using replication slots.

It sounds like there's a good reason to include Rsync. I'll accept a patch. It needs to be added to `ci/Dockerfile` as a minimum, but `Dockerfile` as well if you're planning to use it whilst developing Postgres-XL Docker itself locally.

**Comment by LamaAni** [comment]
PR is up.

**Comment by tiredpixel** [comment]
Merged. Thanks! :)
