### ISSUE TITLE
Official Blessing

### ISSUE THREAD

**Issue by tiredpixel** [pavouk-0/postgres-xl-docker#48]
I respectfully request of the Postgres-XL maintainers that this Postgres-XL Docker project be 'officially blessed'. The project is approximately 2 years old, has 68 stars on GitHub, has 24 forks on GitHub, has 11 watchers on GitHub, has over 100K downloads on Docker Hub (more in previous versions), and is licensed under MIT. In addition, googling for Postgres-XL Docker leads me to a blog post for 2015 (https://www.postgres-xl.org/2015/01/docker-for-postgres-xl/), which lists a link for which DNS is not resolvable.

Although I created the project, I have officially transferred ownership to Pavouk OÜ, a company in Estonia which I am a director of, and which makes Isoxya, a Web Crawler & Data Processing System (https://www.pavouk.tech/). Pavouk donates resources and CI time to build the images, publishes the images to Docker Hub (https://hub.docker.com/u/pavouk0), maintains the code in GitHub (https://github.com/pavouk-0), and publishes announcements on its blog, as part of its commitment to open-source software, to contribute something back to the community.

I would make this request myself personally on the Postgres-XL mailing lists, but despite being reported more than once, those mailing lists (since their migration to the new host, a year or two ago), remain broken for me, since I use the excellent email host Posteo (https://posteo.de/en), who offers a setting to guarantee secure delivery of emails over encryption-through-transit. Since Postgres-XL's mailing list provider doesn't support such, my emails to the list are rejected, and I have ended up unsubscribing. In the early days, I subscribed and manually disabled the security each time when posting, but hopefully it's understandable that this isn't really sustainable (it takes me minutes for each post, signing in via 2FA, etc.). If Postgres-XL's mailing list provider fixed their hosting to be secure, I would happily resubscribe and contribute as before.

I would be grateful if either @sstubbs or @LamaAni would be willing to carry this request to Postgres-XL maintainers on my behalf, they having contributed various accepted patches to this project, over the past year, and to reference this GitHub issue in their request.

Peace, tiredpixel. :)

**Comment by stephenstubbs** [comment]
Hi,

So sorry for the extremely late reply I've been busy getting this working with k8s with the help of @LamaAni and I missed this. I'm now just about completely happy with how it works so I can be more involved with this image as all of our work relies on it.

I'm happy to help with whatever I can however when I've tried to contact the mailing list in the past I get no response. Which one of these https://www.postgres-xl.org/community have you used in the past with success? I will subscribe and contact them about securing it if possible.

**Comment by tiredpixel** [comment]
Thanks. I think I've used both `postgres-xl-developers` and `postgres-xl-general` in the past. I used to sometimes help out with some community questions, until the mailing list was migrated to the new host (a couple of years ago?), which has a broken setup. I reported it, after a while it seemed to get fixed for a while, then it broke again, then I reported it again, then I gave up.

http://lists.postgres-xl.org/pipermail/postgres-xl-developers-postgres-xl.org/2017-August/000492.html
http://lists.postgres-xl.org/pipermail/postgres-xl-developers-postgres-xl.org/2018-January/000581.html

**Comment by LamaAni** [comment]
Have to say, this dose not give confidence in using postgres-xl

**Comment by stephenstubbs** [comment]
Yes it is a bit worrying. I've signed up to all 4. WIll let you know what comes of it.

**Comment by tiredpixel** [comment]
Thanks a lot. :)

**Comment by LamaAni** [comment]
Hi, Any update on this?

**Comment by stephenstubbs** [comment]
Unfortunately no. I sent this http://lists.postgres-xl.org/pipermail/postgres-xl-bugs-postgres-xl.org/2020-January/000501.html but no reply. We've been using Postgres xl for some time and never needed support. 2nd quadrant do provide commercial support if needed but yes if people are going to be using Postgres xl for the first time I would definitely have a second think about it.

**Comment by LamaAni** [comment]
Yea, I agree. I have decided to put a warning on postgres-xl-helm.

**Comment by tiredpixel** [comment]
I'm just wondering: is there any update on this? I'm guessing not. If not, we can close it, as there appears to be very little we can do… :(

**Comment by stephenstubbs** [comment]
Unfortunately not yes this can be closed. I'm am also sad that there is so little response.

**Comment by tiredpixel** [comment]
Yes, it is disappointing. And by no means the first time, in my experience. I'll close. Thanks for trying; much appreciated.
