### ISSUE TITLE
TLS connection between coordinator and datanode.

### ISSUE THREAD

**Issue by aleczmw** [pavouk-0/postgres-xl-docker#49]
Hello,

We would like to use TLS connection between coordinator and datanode, but sslmode is set to disable.(Please find the details in SOURCE CODE)
Does it mean TLS connection can not be set up between coordinator and datanode?
If not how to enable it?

SOURCE CODE:
num = snprintf(connstr, sizeof(connstr),
   "host=%s port=%d dbname=%s user=%s application_name='pgxc:%s' **sslmode=disable** options='-c remotetype=%s -c parentnode=%s %s'",
   host, port, dbname, user, parent_node, remote_type, parent_node,
   pgoptions);

Thanks in advance.

**Comment by tiredpixel** [comment]
@aleczmw , I think this is more a question for the Postgres-XL maintainers themselves; this project is just the Docker packaging. I don't *think* what you're asking is possible in Postgres-XL—but I don't know for sure. Best is probably to ask on their mailing list.

**Comment by tiredpixel** [comment]
Closing as no response.
