### ISSUE TITLE
/bin/sh: 1: ./configure: not found

### ISSUE THREAD

**Issue by dan-developer** [pavouk-0/postgres-xl-docker#50]
The following error occurs when running docker-compose up -d:

 ---> Running in f098e3277884
Removing intermediate container f098e3277884
 ---> 6f700c4eb21f
Step 11/19 : RUN ./configure --prefix ${PG_LIB} &&     make &&     cd contrib/pgxc_monitor &&     make
 ---> Running in 1e0ef355e81a
/bin/sh: 1: ./configure: not found
Service 'db_gtm_1' failed to build: The command '/bin/sh -c ./configure --prefix ${PG_LIB} &&     make &&     cd contrib/pgxc_monitor &&     make' returned a non-zero code: 127

**Comment by tiredpixel** [comment]
@dan-developer , did you remember to clone Git submodules?

**Comment by dan-developer** [comment]
Thanks for answering.

I did not do this step. Is this in the documentation? If you have, I apologize for the inconvenience.

Another thing, the docker swarm worked, compiled correctly. Ref. #51

**Comment by tiredpixel** [comment]
Yes, I think it's here:
https://github.com/pavouk-0/postgres-xl-docker/blob/master/README.md#build
i.e. the `git submodule update` (or using `clone` with the submodule flag should also work)

Glad that it compiled correctly. :)

**Comment by tiredpixel** [comment]
Closing as no response.
