### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by stephenstubbs** [pavouk-0/postgres-xl-docker#53]
Hi,

I'm currently using a custom image internally as I need cube and ltree as we discussed before so this issue doesn't really apply to me as I setup encoding in that image. However I would like to still provide your image for our open source projects and one thing which has given not very nice surprises in the past are encoding issues. 

Would it be possible to include the `locales` package.

Then at init and runtime people can set their encoding like the following if needed
```
sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
```

**Comment by tiredpixel** [comment]
Happy to include `locales`; I believe `postgres` image does already.

Does that mean we'd be able to configure it like in the main PostgreSQL image instructions, 'Locale Customization'? i.e. something like

```
FROM postgres:9.4
RUN localedef -i de_DE -c -f UTF-8 -A /usr/share/locale/locale.alias de_DE.UTF-8
ENV LANG de_DE.utf8
```
https://hub.docker.com/_/postgres

I'll accept a PR.

**Comment by stephenstubbs** [comment]
OK I'll check now if it can be set that way then do a PR

**Comment by stephenstubbs** [comment]
I've been doing some testing. My initial thought was to add all the locales to the image and then have a env variables at run time. It works but it adds an extra 30mb to the image. It is probably better for people to just  extend your image and install the locales package.

**Comment by tiredpixel** [comment]
Okay, sure. Thanks for testing (and apologies for my delayed response). I'll close this issue now, but feel free to reopen or submit a PR if you change your mind.
