### ISSUE TITLE
ERROR: Service 'db_gtm_1' failed to build

### ISSUE THREAD

**Issue by bocktang** [pavouk-0/postgres-xl-docker#58]
I am doing a practise about postgreSQL-XL, followed by your link :  https://github.com/lable/postgres-xl-docker/tree/release-latest, but I got an error like this:

/bin/sh: ./configure: No such file or directory
ERROR: Service 'db_gtm_1' failed to build: The command '/bin/sh -c ./configure --prefix ${PG_LIB}     &&     make     &&     cd contrib/pgxc_ctl     &&     make' returned a non-zero code: 127

it seems that missing a file of configure,

**Comment by tiredpixel** [comment]
`release-latest` branch no longer exists, and this commit is very old. I suggest you update and retry from `master` or one of these branches:
https://github.com/tiredpixel/postgres-xl-docker/branches

Also make sure to check out the Git submodules so `lib/` is populated.
