### ISSUE TITLE
Thought: pooler ports

### ISSUE THREAD

**Issue by tiredpixel** [pavouk-0/postgres-xl-docker#6]
What is the role of the pooler ports, and do they work properly?

**Comment by tiredpixel** [comment]
Still not tested in 0.2.0. If anyone has or would like to investigate this, please say! :)

**Comment by Miazzy** [comment]
Thanks for your seriously & efficiently work , It's really awesome job!

**Comment by tiredpixel** [comment]
I propose closing this, unless it's being actively worked on; it's been open for 2.5 years, without a clear goal (entirely my fault). :)

**Comment by stephenstubbs** [comment]
Yes I'm not working on this.
