### ISSUE TITLE
Thought: slaves

### ISSUE THREAD

**Issue by tiredpixel** [pavouk-0/postgres-xl-docker#8]
Do Coordinator and Datanode Slaves work correctly?

**Comment by tiredpixel** [comment]
Still not tested in 0.2.0. If anyone has or would like to investigate this, please say! :)

**Comment by stephenstubbs** [comment]
I am looking at this now.

**Comment by tiredpixel** [comment]
Thanks a lot! Again, it would be nice to hear anything interesting you discover when looking into this.

**Comment by stephenstubbs** [comment]
I have a working version of this as we talked about before for slaves of gtm, coordinators and datanodes. Will have a look at the helm chart now and see if there is a cleaner way which could work for kubernetes and docker swarm. 

Basically all I'm currently doing is setting an env variable for the MASTER_HOST. If present it creates the config needed and runs as a slave. If the env variable is removed it removes this config which means its now a master (Used for promotion in the event of node corruption). 

Biggest problem is setting up a replication user for this which I currently do via a docker secret  replicationUser, replicationUserPassword. I also have adminUser, adminUserPassword secrets which create/update admin users. I append a version at the end of the secrets for rotation like this https://anthonymineo.com/rotating-your-docker-secrets-can-be-easy-if-you-plan-for-it/ have a small app which generates the passwords and a cronjob that rotates them. However I think using hashicorp vault is a better answer to this.

**Comment by tiredpixel** [comment]
I propose closing this, unless it's being actively worked on; it's been open for 2.5 years, without a clear goal (entirely my fault). :)
