### ISSUE TITLE
Thought: GTM slaves & automated failover

### ISSUE THREAD

**Issue by tiredpixel** [pavouk-0/postgres-xl-docker#9]
How can GTM Slaves and automated failover be achieved?

**Comment by tiredpixel** [comment]
Still not tested in 0.2.0. If anyone has or would like to investigate this, please say! :)

**Comment by stephenstubbs** [comment]
I am looking at this now.

**Comment by tiredpixel** [comment]
Okay, sounds good. I haven't looked into this much, myself, so it would be nice to hear anything interesting you find out during research. :)

**Comment by tiredpixel** [comment]
I propose closing this, unless it's being actively worked on; it's been open for 2.5 years, without a clear goal (entirely my fault). :)

**Comment by stephenstubbs** [comment]
OK makes sense to close it.

The way I was doing it if for reference was:

```
#!/bin/sh -eu
if [ ${PG_MASTER_HOST+"false"} ]
then
        test -d "$PGDATA" || docker-init-gtm
        sed -i "s|#startup = ACT|startup = STANDBY|" "${PGDATA}/gtm.conf"
        sed -i "s|#active_host = ''|active_host = '${PG_MASTER_HOST}'|" "${PGDATA}/gtm.conf"
        sed -i "s|#active_port =|active_port = 6666|" "${PGDATA}/gtm.conf"
else
        test -d "$PGDATA" || docker-init-gtm
        sed -i "s|startup = STANDBY|#startup = ACT|" "${PGDATA}/gtm.conf"
        sed -i "s|active_host = '*|#active_host = ''|" "${PGDATA}/gtm.conf"
        sed -i "s|active_port = 6666|#active_port =|" "${PGDATA}/gtm.conf"
fi

exec "$@"
```
